[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    clear_session: чистит куки и/или storage домена перед тестом. args: url. kwargs: strategy=cookies|full (default: cookies)
